import type { Prisma } from "@prisma/client";
import { Router } from "express";
import { prisma } from "../lib/prisma";
import { requireAdmin } from "../middleware/requireAdmin";
import { fetchProductByEan } from "../services/OpenFoodFacts";

export const adminProductsRouter = Router();

adminProductsRouter.post("/api/admin/aisles", requireAdmin, async (req, res) => {
  try {
    const { name, code } = req.body as { name?: string; code?: string };
    if (!name || typeof name !== "string" || !name.trim()) {
      res.status(400).json({ error: "Aisle name is required" });
      return;
    }
    const normalizedName = name.trim();
    const existingByName = await prisma.aisle.findFirst({
      where: {
        name: {
          equals: normalizedName,
          mode: "insensitive",
        },
      },
      select: { id: true },
    });
    if (existingByName) {
      res.status(409).json({ error: "Aisle name already exists" });
      return;
    }

    const baseCode =
      (typeof code === "string" && code.trim()
        ? code.trim()
        : normalizedName
            .toUpperCase()
            .replace(/\s+/g, "-")
            .replace(/[^A-Z0-9-]/g, "")
            .slice(0, 12)) || "AISLE";
    let normalizedCode = baseCode;
    let suffix = 2;
    // Ensure unique code even when autogenerated.
    while (true) {
      const existing = await prisma.aisle.findFirst({
        where: { code: normalizedCode },
        select: { id: true },
      });
      if (!existing) break;
      normalizedCode = `${baseCode}-${suffix}`;
      suffix += 1;
    }

    const aisle = await prisma.aisle.create({
      data: {
        name: normalizedName,
        code: normalizedCode,
      },
      select: { id: true, name: true, code: true },
    });

    res.status(201).json(aisle);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Internal server error" });
  }
});

adminProductsRouter.get("/api/admin/layout/options", requireAdmin, async (_req, res) => {
  try {
    const [aisles, sections, shelves] = await Promise.all([
      prisma.aisle.findMany({
        orderBy: { name: "asc" },
        select: { id: true, name: true, code: true },
      }),
      prisma.section.findMany({
        orderBy: { name: "asc" },
        include: {
          aisle: {
            select: { id: true, name: true, code: true },
          },
        },
      }),
      prisma.shelf.findMany({
        orderBy: [{ name: "asc" }],
        include: {
          section: {
            include: {
              aisle: {
                select: { id: true, name: true, code: true },
              },
            },
          },
        },
      }),
    ]);

    res.json({ aisles, sections, shelves });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Internal server error" });
  }
});

adminProductsRouter.post("/api/admin/sections", requireAdmin, async (req, res) => {
  try {
    const { name, aisleId, aisleName, aisleCode } = req.body as {
      name?: string;
      aisleId?: number;
      aisleName?: string;
      aisleCode?: string;
    };
    if (!name || typeof name !== "string" || !name.trim()) {
      res.status(400).json({ error: "Section name is required" });
      return;
    }
    const normalizedSectionName = name.trim();
    const existingSectionByName = await prisma.section.findFirst({
      where: {
        name: {
          equals: normalizedSectionName,
          mode: "insensitive",
        },
      },
      select: { id: true },
    });
    if (existingSectionByName) {
      res.status(409).json({ error: "Section name already exists" });
      return;
    }

    let parsedAisleId: number;
    const explicitAisleId = Number(aisleId);
    if (!Number.isNaN(explicitAisleId)) {
      const aisle = await prisma.aisle.findUnique({
        where: { id: explicitAisleId },
        select: { id: true },
      });
      if (!aisle) {
        res.status(400).json({ error: "Aisle does not exist" });
        return;
      }
      parsedAisleId = explicitAisleId;
    } else {
      const fallbackAisleName =
        aisleName && aisleName.trim() ? aisleName.trim() : "Frikopplad gång";
      const fallbackAisleCode =
        aisleCode && aisleCode.trim() ? aisleCode.trim() : "FREE";
      const existingAisle = await prisma.aisle.findFirst({
        where: { code: fallbackAisleCode },
        select: { id: true },
      });
      if (existingAisle) {
        parsedAisleId = existingAisle.id;
      } else {
        const createdAisle = await prisma.aisle.create({
          data: {
            name: fallbackAisleName,
            code: fallbackAisleCode,
          },
          select: { id: true },
        });
        parsedAisleId = createdAisle.id;
      }
    }

    const section = await prisma.section.create({
      data: {
        name: normalizedSectionName,
        aisleId: parsedAisleId,
      },
      include: {
        aisle: {
          select: { id: true, name: true, code: true },
        },
      },
    });

    res.status(201).json(section);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Internal server error" });
  }
});

adminProductsRouter.post("/api/admin/shelves", requireAdmin, async (req, res) => {
  try {
    const { name } = req.body as {
      name?: string;
    };
    if (!name || typeof name !== "string" || !name.trim()) {
      res.status(400).json({ error: "Shelf name is required" });
      return;
    }
    const normalizedShelfName = name.trim();
    const existingShelfByName = await prisma.shelf.findFirst({
      where: {
        name: {
          equals: normalizedShelfName,
          mode: "insensitive",
        },
      },
      select: { id: true },
    });
    if (existingShelfByName) {
      res.status(409).json({ error: "Shelf name already exists" });
      return;
    }

    const defaultAisleCode = "FREE";
    let defaultAisle = await prisma.aisle.findFirst({
      where: { code: defaultAisleCode },
      select: { id: true },
    });
    if (!defaultAisle) {
      defaultAisle = await prisma.aisle.create({
        data: { name: "Frikopplad gång", code: defaultAisleCode },
        select: { id: true },
      });
    }
    let defaultSection = await prisma.section.findFirst({
      where: {
        name: "Frikopplad sektion",
        aisleId: defaultAisle.id,
      },
      select: { id: true },
    });
    if (!defaultSection) {
      defaultSection = await prisma.section.create({
        data: { name: "Frikopplad sektion", aisleId: defaultAisle.id },
        select: { id: true },
      });
    }

    const shelf = await prisma.shelf.create({
      data: {
        name: normalizedShelfName,
        sectionId: defaultSection.id,
        level: 1,
        position: null,
      },
      include: {
        section: {
          include: {
            aisle: true,
          },
        },
      },
    });

    res.status(201).json(shelf);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Internal server error" });
  }
});

adminProductsRouter.post("/api/admin/products", requireAdmin, async (req, res) => {
  try {
    const { ean, shelfId, aisleName, sectionName, shelfLabel, position } = req.body as {
      ean?: string;
      shelfId?: number;
      aisleName?: string;
      sectionName?: string;
      shelfLabel?: string;
      position?: number;
    };

    if (!ean || typeof ean !== "string" || !ean.trim()) {
      res.status(400).json({ error: "EAN is required" });
      return;
    }

    const normalizedEan = ean.trim().replace(/\s/g, "");
    if (normalizedEan.length < 8) {
      res.status(400).json({ error: "Invalid EAN" });
      return;
    }

    const existing = await prisma.product.findUnique({
      where: { ean: normalizedEan },
    });
    if (existing) {
      res.status(409).json({
        error: "Product already exists",
        productId: existing.id,
      });
      return;
    }

    const offProduct = await fetchProductByEan(normalizedEan);

    if (!offProduct) {
      res.status(404).json({
        error:
          "Could not find product in Open Food Facts, please check the EAN",
      });
      return;
    }

    const name = offProduct.name;
    const brand = offProduct.brand;
    const description = offProduct.description;
    const categoryName = offProduct.categoryName;

    let category = await prisma.category.findFirst({
      where: { name: categoryName },
    });
    if (!category) {
      category = await prisma.category.create({
        data: { name: categoryName },
      });
    }

    if (shelfId != null) {
      if (!Number.isInteger(shelfId)) {
        res.status(400).json({ error: "Invalid shelfId" });
        return;
      }
      const shelf = await prisma.shelf.findUnique({
        where: { id: shelfId },
        select: { id: true },
      });
      if (!shelf) {
        res.status(400).json({
          error: "Shelf does not exist",
          missingShelfId: shelfId,
        });
        return;
      }
    }

    const product = await prisma.$transaction(async (tx) => {
      const created = await tx.product.create({
        data: {
          ean: normalizedEan,
          openFoodFactsId: offProduct.openFoodFactsId,
          name,
          brand,
          description,
          imageUrl: offProduct.imageUrl || null,
          categoryId: category.id,
        },
      });

      if (
        shelfId != null ||
        (aisleName && aisleName.trim()) ||
        (sectionName && sectionName.trim()) ||
        (shelfLabel && shelfLabel.trim())
      ) {
        await tx.productLocation.create({
          data: {
            productId: created.id,
            shelfId: shelfId ?? null,
            aisleName: aisleName?.trim() || null,
            sectionName: sectionName?.trim() || null,
            shelfLabel: shelfLabel?.trim() || null,
            position: typeof position === "number" ? position : null,
          },
        });
      }

      return created;
    });

    const productWithLocation = await prisma.product.findUnique({
      where: { id: product.id },
      include: {
        category: true,
        locations: {
          include: {
            shelf: {
              include: {
                section: { include: { aisle: true } },
              },
            },
          },
        },
      },
    });

    res.status(201).json(productWithLocation);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Internal server error" });
  }
});

adminProductsRouter.put("/api/admin/products/:id", requireAdmin, async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (Number.isNaN(id)) {
      res.status(400).json({ error: "Invalid id" });
      return;
    }

    const { name, brand, description, categoryId } = req.body as {
      name?: string;
      brand?: string;
      description?: string;
      categoryId?: number;
    };

    const data: Prisma.ProductUpdateInput = {};

    if (typeof name === "string" && name.trim()) {
      data.name = name.trim();
    }
    if (typeof brand === "string") {
      data.brand = brand.trim();
    }
    if (typeof description === "string") {
      data.description = description.trim();
    }

    if (categoryId != null) {
      const catId = Number(categoryId);
      if (Number.isNaN(catId)) {
        res.status(400).json({ error: "Invalid categoryId" });
        return;
      }
      const category = await prisma.category.findUnique({
        where: { id: catId },
      });
      if (!category) {
        res.status(400).json({ error: "Category not found" });
        return;
      }
      data.category = { connect: { id: category.id } };
    }

    if (Object.keys(data).length === 0) {
      res.status(400).json({ error: "No fields to update" });
      return;
    }

    const updated = await prisma.product.update({
      where: { id },
      data,
      include: {
        category: true,
        locations: {
          include: {
            shelf: {
              include: {
                section: { include: { aisle: true } },
              },
            },
          },
        },
      },
    });

    res.json(updated);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Internal server error" });
  }
});

adminProductsRouter.delete("/api/admin/products/:id", requireAdmin, async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (Number.isNaN(id)) {
      res.status(400).json({ error: "Invalid id" });
      return;
    }

    const product = await prisma.product.findUnique({
      where: { id },
    });

    if (!product) {
      res.status(404).json({ error: "Product not found" });
      return;
    }

    await prisma.productLocation.deleteMany({
      where: { productId: id },
    });

    await prisma.product.delete({
      where: { id },
    });

    res.status(204).end();
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Internal server error" });
  }
});

adminProductsRouter.put(
  "/api/admin/products/:id/locations",
  requireAdmin,
  async (req, res) => {
    try {
      const id = Number(req.params.id);
      if (Number.isNaN(id)) {
        res.status(400).json({ error: "Invalid id" });
        return;
      }
      const { locations } = req.body as {
        locations?: {
          shelfId?: number;
          position?: number;
          aisleName?: string;
          sectionName?: string;
          shelfLabel?: string;
        }[];
      };
      if (!Array.isArray(locations) || locations.length === 0) {
        res
          .status(400)
          .json({ error: "locations needs to be a non empty array" });
        return;
      }

      const product = await prisma.product.findUnique({
        where: { id },
      });
      if (!product) {
        res.status(404).json({ error: "Product not found" });
        return;
      }

      const shelfIds = locations
        .map((loc) => (loc.shelfId != null ? Number(loc.shelfId) : null))
        .filter((sid): sid is number => sid != null);
      if (shelfIds.some((sid) => Number.isNaN(sid))) {
        res.status(400).json({ error: "Invalid shelfId in locations" });
        return;
      }
      if (shelfIds.length > 0) {
        const distinctShelfIds = Array.from(new Set(shelfIds));
        const shelves = await prisma.shelf.findMany({
          where: { id: { in: distinctShelfIds } },
          select: { id: true },
        });
        const existingShelfIds = new Set(shelves.map((s) => s.id));
        const missing = distinctShelfIds.filter((sid) => !existingShelfIds.has(sid));
        if (missing.length > 0) {
          res.status(400).json({
            error: "Following shelfId does not exist",
            missingShelfIds: missing,
          });
          return;
        }
      }

      await prisma.$transaction([
        prisma.productLocation.deleteMany({
          where: { productId: id },
        }),
        prisma.productLocation.createMany({
          data: locations.map((loc) => ({
            productId: id,
            shelfId: loc.shelfId != null ? Number(loc.shelfId) : null,
            aisleName: loc.aisleName?.trim() || null,
            sectionName: loc.sectionName?.trim() || null,
            shelfLabel: loc.shelfLabel?.trim() || null,
            position: typeof loc.position === "number" ? loc.position : null,
          })),
        }),
      ]);

      const updated = await prisma.product.findUnique({
        where: { id },
        include: {
          category: true,
          locations: {
            include: {
              shelf: {
                include: {
                  section: { include: { aisle: true } },
                },
              },
            },
          },
        },
      });
      res.json(updated);
    } catch (err) {
      console.error(err);
      res.status(500).json({ error: "Internal server error" });
    }
  },
);

adminProductsRouter.post(
  "/api/admin/products/:id/locations",
  requireAdmin,
  async (req, res) => {
    try {
      const id = Number(req.params.id);
      if (Number.isNaN(id)) {
        res.status(400).json({ error: "Invalid id" });
        return;
      }

      const { shelfId, aisleName, sectionName, shelfLabel, position } = req.body as {
        shelfId?: number;
        aisleName?: string;
        sectionName?: string;
        shelfLabel?: string;
        position?: number;
      };

      const product = await prisma.product.findUnique({
        where: { id },
        select: { id: true },
      });
      if (!product) {
        res.status(404).json({ error: "Product not found" });
        return;
      }

      if (shelfId != null) {
        const parsedShelfId = Number(shelfId);
        if (Number.isNaN(parsedShelfId)) {
          res.status(400).json({ error: "Invalid shelfId" });
          return;
        }
        const shelf = await prisma.shelf.findUnique({
          where: { id: parsedShelfId },
          select: { id: true },
        });
        if (!shelf) {
          res.status(400).json({ error: "Shelf does not exist" });
          return;
        }
      }

      const createdLocation = await prisma.productLocation.create({
        data: {
          productId: id,
          shelfId: shelfId != null ? Number(shelfId) : null,
          aisleName: aisleName?.trim() || null,
          sectionName: sectionName?.trim() || null,
          shelfLabel: shelfLabel?.trim() || null,
          position: typeof position === "number" ? position : null,
        },
      });

      res.status(201).json(createdLocation);
    } catch (err) {
      console.error(err);
      res.status(500).json({ error: "Internal server error" });
    }
  },
);

adminProductsRouter.put(
  "/api/admin/products/:id/locations/:locationId",
  requireAdmin,
  async (req, res) => {
    try {
      const id = Number(req.params.id);
      const locationId = Number(req.params.locationId);
      if (Number.isNaN(id) || Number.isNaN(locationId)) {
        res.status(400).json({ error: "Invalid id" });
        return;
      }

      const existing = await prisma.productLocation.findFirst({
        where: { id: locationId, productId: id },
        select: { id: true },
      });
      if (!existing) {
        res.status(404).json({ error: "Product location not found" });
        return;
      }

      const { shelfId, aisleName, sectionName, shelfLabel, position } = req.body as {
        shelfId?: number;
        aisleName?: string;
        sectionName?: string;
        shelfLabel?: string;
        position?: number;
      };

      if (shelfId != null) {
        const parsedShelfId = Number(shelfId);
        if (Number.isNaN(parsedShelfId)) {
          res.status(400).json({ error: "Invalid shelfId" });
          return;
        }
        const shelf = await prisma.shelf.findUnique({
          where: { id: parsedShelfId },
          select: { id: true },
        });
        if (!shelf) {
          res.status(400).json({ error: "Shelf does not exist" });
          return;
        }
      }

      const updated = await prisma.productLocation.update({
        where: { id: locationId },
        data: {
          shelfId: shelfId != null ? Number(shelfId) : null,
          aisleName: aisleName?.trim() || null,
          sectionName: sectionName?.trim() || null,
          shelfLabel: shelfLabel?.trim() || null,
          position: typeof position === "number" ? position : null,
        },
      });
      res.json(updated);
    } catch (err) {
      console.error(err);
      res.status(500).json({ error: "Internal server error" });
    }
  },
);

adminProductsRouter.delete(
  "/api/admin/products/:id/locations/:locationId",
  requireAdmin,
  async (req, res) => {
    try {
      const id = Number(req.params.id);
      const locationId = Number(req.params.locationId);
      if (Number.isNaN(id) || Number.isNaN(locationId)) {
        res.status(400).json({ error: "Invalid id" });
        return;
      }

      const existing = await prisma.productLocation.findFirst({
        where: { id: locationId, productId: id },
        select: { id: true },
      });
      if (!existing) {
        res.status(404).json({ error: "Product location not found" });
        return;
      }

      await prisma.productLocation.delete({
        where: { id: locationId },
      });
      res.status(204).end();
    } catch (err) {
      console.error(err);
      res.status(500).json({ error: "Internal server error" });
    }
  },
);

